### ISSUE TITLE
Documentation lacks correct login information

### ISSUE THREAD

**Issue by mjbright** [jenkinsci/docker#2043]
### Describe your use-case which is not covered by existing documentation.

Following the repo README.md, I launch the Jenkins docker container (named as ```jenkins```) as below

Launched as:
```
docker run -d -v jenkins_home:/var/jenkins_home --name jenkins -p 8080:8080 -p 50000:50000 --restart=on-failure jenkins/jenkins:lts-jdk17
```

In the README.md text it is written:
```
This will run Jenkins in detached mode with port forwarding and volume added. You can access logs with command 'docker logs CONTAINER_ID' in order to check first login token. ID of container will be returned from output of command above.
```

But looking at the docker logs has no mention of login/token/admin/pass ...

The documentation should
- be correct of course
- provide an example log line to be explicit about what noobs should be looking for

Attempt to find anything related to login info:
```
docker logs jenkins |& grep -iE "admin|token|login|pass"
2025-07-10 06:41:59.747+0000 [id=1]     INFO    winstone.Logger#logInternal: Beginning extraction from war file
2025-07-10 06:42:03.512+0000 [id=24]    INFO    winstone.Logger#logInternal: Winstone Servlet Engine running: controlPort=disabled
```

Also tried with the latest jdk21 image - same result.

**Comment by dduportal** [comment]
Your `grep` pattern is too restrictive and you should look at the raw logs. Search for somethig looking like this:

```
*************************************************************
*************************************************************
*************************************************************

Jenkins initial setup is required. An admin user has been created and a password generated.
Please use the following password to proceed to installation:

<redacted token>

This may also be found at: /var/jenkins_home/secrets/initialAdminPassword

*************************************************************
*************************************************************
*************************************************************
```


Full example:

```bash
$ docker run -d -v jenkins_home:/var/jenkins_home --name jenkins -p 8080:8080 -p 50000:50000 --restart=on-failure jenkins/jenkins:lts-jdk17
Unable to find image 'jenkins/jenkins:lts-jdk17' locally
lts-jdk17: Pulling from jenkins/jenkins
8fbf1dd6492c: Pull complete 
77940aee1d27: Pull complete 
7fbfa1e99bdc: Pull complete 
e50f74d6edbf: Pull complete 
af0d117b319b: Pull complete 
7af9cf978d7a: Pull complete 
2de0d578cae3: Pull complete 
07f0af7761da: Pull complete 
34046e5efc66: Pull complete 
c6de55c54b9c: Pull complete 
cff4d5c73dbe: Pull complete 
45aa5d951025: Pull complete 
Digest: sha256:dd570585c3adadefcfbeba915e27bf7feca1815a0ea8a659d46b51f54fc7ea06
Status: Downloaded newer image for jenkins/jenkins:lts-jdk17
14a28289778568a20efeadae2bf738faeb95ff1f32ecd6eb748717aca8bfe72d
$ docker logs 14a28289778568a20efeadae2bf738faeb95ff1f32ecd6eb748717aca8bfe72d
Running from: /usr/share/jenkins/jenkins.war
webroot: /var/jenkins_home/war
2025-07-10 07:17:44.148+0000 [id=1]     INFO    winstone.Logger#logInternal: Beginning extraction from war file
2025-07-10 07:17:44.548+0000 [id=1]     WARNING o.e.j.ee9.nested.ContextHandler#setContextPath: Empty contextPath
2025-07-10 07:17:44.569+0000 [id=1]     INFO    org.eclipse.jetty.server.Server#doStart: jetty-12.0.22; built: 2025-06-02T15:25:31.946Z; git: 335c9ab44a5591f0ea941bf350e139b8c4f5537c; jvm 17.0.15+6
2025-07-10 07:17:44.752+0000 [id=1]     INFO    o.e.j.e.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /, did not find org.eclipse.jetty.ee9.jsp.JettyJspServlet
2025-07-10 07:17:44.774+0000 [id=1]     INFO    o.e.j.s.DefaultSessionIdManager#doStart: Session workerName=node0
2025-07-10 07:17:44.979+0000 [id=1]     INFO    hudson.WebAppMain#contextInitialized: Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
2025-07-10 07:17:45.027+0000 [id=1]     INFO    o.e.j.s.handler.ContextHandler#doStart: Started oeje9n.ContextHandler$CoreContextHandler@23382f76{Jenkins v2.504.3,/,b=file:///var/jenkins_home/war/,a=AVAILABLE,h=oeje9n.ContextHandler$CoreContextHandler$CoreToNestedHandler@7c551ad4{STARTED}}
2025-07-10 07:17:45.036+0000 [id=1]     INFO    o.e.j.server.AbstractConnector#doStart: Started ServerConnector@4eb45fec{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2025-07-10 07:17:45.046+0000 [id=1]     INFO    org.eclipse.jetty.server.Server#doStart: Started oejs.Server@53f0a4cb{STARTING}[12.0.22,sto=0] @1166ms
2025-07-10 07:17:45.046+0000 [id=26]    INFO    winstone.Logger#logInternal: Winstone Servlet Engine running: controlPort=disabled
2025-07-10 07:17:45.120+0000 [id=25]    INFO    jenkins.model.Jenkins#<init>: Starting version 2.504.3
2025-07-10 07:17:45.171+0000 [id=34]    INFO    jenkins.InitReactorRunner$1#onAttained: Started initialization
2025-07-10 07:17:45.178+0000 [id=42]    INFO    jenkins.InitReactorRunner$1#onAttained: Listed all plugins
2025-07-10 07:17:45.495+0000 [id=42]    INFO    jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
2025-07-10 07:17:45.496+0000 [id=42]    INFO    jenkins.InitReactorRunner$1#onAttained: Started all plugins
2025-07-10 07:17:45.496+0000 [id=34]    INFO    jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
2025-07-10 07:17:45.577+0000 [id=39]    INFO    jenkins.InitReactorRunner$1#onAttained: System config loaded
2025-07-10 07:17:45.578+0000 [id=39]    INFO    jenkins.InitReactorRunner$1#onAttained: System config adapted
2025-07-10 07:17:45.578+0000 [id=39]    INFO    jenkins.InitReactorRunner$1#onAttained: Loaded all jobs
2025-07-10 07:17:45.578+0000 [id=39]    INFO    jenkins.InitReactorRunner$1#onAttained: Configuration for all jobs updated
2025-07-10 07:17:45.592+0000 [id=61]    INFO    hudson.util.Retrier#start: Attempt #1 to do the action check updates server
2025-07-10 07:17:45.866+0000 [id=34]    INFO    jenkins.install.SetupWizard#init: 

*************************************************************
*************************************************************
*************************************************************

Jenkins initial setup is required. An admin user has been created and a password generated.
Please use the following password to proceed to installation:

<redacted token>

This may also be found at: /var/jenkins_home/secrets/initialAdminPassword

*************************************************************
*************************************************************
*************************************************************

2025-07-10 07:17:47.881+0000 [id=34]    INFO    jenkins.InitReactorRunner$1#onAttained: Completed initialization
2025-07-10 07:17:47.905+0000 [id=25]    INFO    hudson.lifecycle.Lifecycle#onReady: Jenkins is fully up and running
2025-07-10 07:17:48.614+0000 [id=61]    INFO    h.m.DownloadService$Downloadable#load: Obtained the updated data file for hudson.tasks.Maven.MavenInstaller
2025-07-10 07:17:48.614+0000 [id=61]    INFO    hudson.util.Retrier#start: Performed the action check updates server successfully at the attempt #1312
```

**Comment by dduportal** [comment]
I guess you are expecting the README to point to https://www.jenkins.io/doc/book/installing/docker/ if I'm not mistaken.

Ping @kmartens27 @MarkEWaite @gounthar @timja  WDYT: Shouldn't we link the jenkins.io documentation to guide beginners (instead of duplicating "get started" info here)?

**Comment by timja** [comment]
I think simple getting started should be here and then more detail on jenkins.io.

**Comment by mjbright** [comment]
> Your `grep` pattern is too restrictive and you should look at the raw logs. Search for somethig looking like this:
> 
> ```
> *************************************************************
> *************************************************************
> *************************************************************
> 
> Jenkins initial setup is required. An admin user has been created and a password generated.
> Please use the following password to proceed to installation:
> 
> <redacted token>
> 
> This may also be found at: /var/jenkins_home/secrets/initialAdminPassword
> 
> *************************************************************
> *************************************************************
> *************************************************************
> ```
> 
> Full example:
> 
> $ docker run -d -v jenkins_home:/var/jenkins_home --name jenkins -p 8080:8080 -p 50000:50000 --restart=on-failure jenkins/jenkins:lts-jdk17
> Unable to find image 'jenkins/jenkins:lts-jdk17' locally
> lts-jdk17: Pulling from jenkins/jenkins
> 8fbf1dd6492c: Pull complete 
> 77940aee1d27: Pull complete 
> 7fbfa1e99bdc: Pull complete 
> e50f74d6edbf: Pull complete 
> af0d117b319b: Pull complete 
> 7af9cf978d7a: Pull complete 
> 2de0d578cae3: Pull complete 
> 07f0af7761da: Pull complete 
> 34046e5efc66: Pull complete 
> c6de55c54b9c: Pull complete 
> cff4d5c73dbe: Pull complete 
> 45aa5d951025: Pull complete 
> Digest: sha256:dd570585c3adadefcfbeba915e27bf7feca1815a0ea8a659d46b51f54fc7ea06
> Status: Downloaded newer image for jenkins/jenkins:lts-jdk17
> 14a28289778568a20efeadae2bf738faeb95ff1f32ecd6eb748717aca8bfe72d
> $ docker logs 14a28289778568a20efeadae2bf738faeb95ff1f32ecd6eb748717aca8bfe72d
> Running from: /usr/share/jenkins/jenkins.war
> webroot: /var/jenkins_home/war
> 2025-07-10 07:17:44.148+0000 [id=1]     INFO    winstone.Logger#logInternal: Beginning extraction from war file
> 2025-07-10 07:17:44.548+0000 [id=1]     WARNING o.e.j.ee9.nested.ContextHandler#setContextPath: Empty contextPath
> 2025-07-10 07:17:44.569+0000 [id=1]     INFO    org.eclipse.jetty.server.Server#doStart: jetty-12.0.22; built: 2025-06-02T15:25:31.946Z; git: 335c9ab44a5591f0ea941bf350e139b8c4f5537c; jvm 17.0.15+6
> 2025-07-10 07:17:44.752+0000 [id=1]     INFO    o.e.j.e.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /, did not find org.eclipse.jetty.ee9.jsp.JettyJspServlet
> 2025-07-10 07:17:44.774+0000 [id=1]     INFO    o.e.j.s.DefaultSessionIdManager#doStart: Session workerName=node0
> 2025-07-10 07:17:44.979+0000 [id=1]     INFO    hudson.WebAppMain#contextInitialized: Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
> 2025-07-10 07:17:45.027+0000 [id=1]     INFO    o.e.j.s.handler.ContextHandler#doStart: Started oeje9n.ContextHandler$CoreContextHandler@23382f76{Jenkins v2.504.3,/,b=file:///var/jenkins_home/war/,a=AVAILABLE,h=oeje9n.ContextHandler$CoreContextHandler$CoreToNestedHandler@7c551ad4{STARTED}}
> 2025-07-10 07:17:45.036+0000 [id=1]     INFO    o.e.j.server.AbstractConnector#doStart: Started ServerConnector@4eb45fec{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
> 2025-07-10 07:17:45.046+0000 [id=1]     INFO    org.eclipse.jetty.server.Server#doStart: Started oejs.Server@53f0a4cb{STARTING}[12.0.22,sto=0] @1166ms
> 2025-07-10 07:17:45.046+0000 [id=26]    INFO    winstone.Logger#logInternal: Winstone Servlet Engine running: controlPort=disabled
> 2025-07-10 07:17:45.120+0000 [id=25]    INFO    jenkins.model.Jenkins#<init>: Starting version 2.504.3
> 2025-07-10 07:17:45.171+0000 [id=34]    INFO    jenkins.InitReactorRunner$1#onAttained: Started initialization
> 2025-07-10 07:17:45.178+0000 [id=42]    INFO    jenkins.InitReactorRunner$1#onAttained: Listed all plugins
> 2025-07-10 07:17:45.495+0000 [id=42]    INFO    jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
> 2025-07-10 07:17:45.496+0000 [id=42]    INFO    jenkins.InitReactorRunner$1#onAttained: Started all plugins
> 2025-07-10 07:17:45.496+0000 [id=34]    INFO    jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
> 2025-07-10 07:17:45.577+0000 [id=39]    INFO    jenkins.InitReactorRunner$1#onAttained: System config loaded
> 2025-07-10 07:17:45.578+0000 [id=39]    INFO    jenkins.InitReactorRunner$1#onAttained: System config adapted
> 2025-07-10 07:17:45.578+0000 [id=39]    INFO    jenkins.InitReactorRunner$1#onAttained: Loaded all jobs
> 2025-07-10 07:17:45.578+0000 [id=39]    INFO    jenkins.InitReactorRunner$1#onAttained: Configuration for all jobs updated
> 2025-07-10 07:17:45.592+0000 [id=61]    INFO    hudson.util.Retrier#start: Attempt #1 to do the action check updates server
> 2025-07-10 07:17:45.866+0000 [id=34]    INFO    jenkins.install.SetupWizard#init: 
> 
> *************************************************************
> *************************************************************
> *************************************************************
> 
> Jenkins initial setup is required. An admin user has been created and a password generated.
> Please use the following password to proceed to installation:
> 
> <redacted token>
> 
> This may also be found at: /var/jenkins_home/secrets/initialAdminPassword
> 
> *************************************************************
> *************************************************************
> *************************************************************
> 
> 2025-07-10 07:17:47.881+0000 [id=34]    INFO    jenkins.InitReactorRunner$1#onAttained: Completed initialization
> 2025-07-10 07:17:47.905+0000 [id=25]    INFO    hudson.lifecycle.Lifecycle#onReady: Jenkins is fully up and running
> 2025-07-10 07:17:48.614+0000 [id=61]    INFO    h.m.DownloadService$Downloadable#load: Obtained the updated data file for hudson.tasks.Maven.MavenInstaller
> 2025-07-10 07:17:48.614+0000 [id=61]    INFO    hudson.util.Retrier#start: Performed the action check updates server successfully at the attempt #1312


Hi Damien - long time no see - well, the full log is as follows, there is no token info there:

```
 docker logs jenkins
Running from: /usr/share/jenkins/jenkins.war
webroot: /var/jenkins_home/war
2025-07-10 06:41:59.747+0000 [id=1]     INFO    winstone.Logger#logInternal: Beginning extraction from war file
2025-07-10 06:42:01.105+0000 [id=1]     WARNING o.e.j.ee9.nested.ContextHandler#setContextPath: Empty contextPath
2025-07-10 06:42:01.214+0000 [id=1]     INFO    org.eclipse.jetty.server.Server#doStart: jetty-12.0.22; built: 2025-06-02T15:25:31.946Z; git: 335c9ab44a5591f0ea941bf350e139b8c4f5537c; jvm 17.0.15+6
2025-07-10 06:42:02.117+0000 [id=1]     INFO    o.e.j.e.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /, did not find org.eclipse.jetty.ee9.jsp.JettyJspServlet
2025-07-10 06:42:02.212+0000 [id=1]     INFO    o.e.j.s.DefaultSessionIdManager#doStart: Session workerName=node0
2025-07-10 06:42:03.208+0000 [id=1]     INFO    hudson.WebAppMain#contextInitialized: Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
2025-07-10 06:42:03.426+0000 [id=1]     INFO    o.e.j.s.handler.ContextHandler#doStart: Started oeje9n.ContextHandler$CoreContextHandler@23382f76{Jenkins v2.504.3,/,b=file:///var/jenkins_home/war/,a=AVAILABLE,h=oeje9n.ContextHandler$CoreContextHandler$CoreToNestedHandler@7c551ad4{STARTED}}
2025-07-10 06:42:03.492+0000 [id=1]     INFO    o.e.j.server.AbstractConnector#doStart: Started ServerConnector@4eb45fec{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2025-07-10 06:42:03.510+0000 [id=1]     INFO    org.eclipse.jetty.server.Server#doStart: Started oejs.Server@53f0a4cb{STARTING}[12.0.22,sto=0] @4908ms
2025-07-10 06:42:03.512+0000 [id=24]    INFO    winstone.Logger#logInternal: Winstone Servlet Engine running: controlPort=disabled
2025-07-10 06:42:03.675+0000 [id=23]    INFO    jenkins.model.Jenkins#<init>: Starting version 2.504.3
2025-07-10 06:42:03.780+0000 [id=31]    INFO    jenkins.InitReactorRunner$1#onAttained: Started initialization
2025-07-10 06:42:04.048+0000 [id=32]    INFO    jenkins.InitReactorRunner$1#onAttained: Listed all plugins
2025-07-10 06:42:08.763+0000 [id=29]    INFO    jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
2025-07-10 06:42:08.802+0000 [id=32]    INFO    jenkins.InitReactorRunner$1#onAttained: Started all plugins
2025-07-10 06:42:08.885+0000 [id=31]    INFO    jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
2025-07-10 06:42:10.182+0000 [id=30]    INFO    h.p.b.g.GlobalTimeOutConfiguration#load: global timeout not set
2025-07-10 06:42:12.212+0000 [id=29]    INFO    jenkins.InitReactorRunner$1#onAttained: System config loaded
2025-07-10 06:42:12.212+0000 [id=29]    INFO    jenkins.InitReactorRunner$1#onAttained: System config adapted
2025-07-10 06:42:12.307+0000 [id=29]    INFO    jenkins.InitReactorRunner$1#onAttained: Loaded all jobs
2025-07-10 06:42:12.311+0000 [id=29]    INFO    jenkins.InitReactorRunner$1#onAttained: Configuration for all jobs updated
2025-07-10 06:42:12.402+0000 [id=30]    INFO    jenkins.InitReactorRunner$1#onAttained: Completed initialization
2025-07-10 06:42:12.540+0000 [id=23]    INFO    hudson.lifecycle.Lifecycle#onReady: Jenkins is fully up and running
```

**Comment by mjbright** [comment]
> I guess you are expecting the README to point to https://www.jenkins.io/doc/book/installing/docker/ if I'm not mistaken.
> 
> Ping [@kmartens27](https://github.com/kmartens27) [@MarkEWaite](https://github.com/MarkEWaite) [@gounthar](https://github.com/gounthar) [@timja](https://github.com/timja) WDYT: Shouldn't we link the jenkins.io documentation to guide beginners (instead of duplicating "get started" info here)?

... thanks, having a look there ...

**Comment by dduportal** [comment]
@mjbright You might want to check from an empty volume: the logs here show it reusing an existing JENKINS_HOME, or setup wizard disabled (through a file in a `Dockerfile` or environment variable).

What is the full `docker` command you're using exactly?


> Hi Damien - long time no see

👋  Same :)

**Comment by mjbright** [comment]
> > I guess you are expecting the README to point to https://www.jenkins.io/doc/book/installing/docker/ if I'm not mistaken.
> > Ping [@kmartens27](https://github.com/kmartens27) [@MarkEWaite](https://github.com/MarkEWaite) [@gounthar](https://github.com/gounthar) [@timja](https://github.com/timja) WDYT: Shouldn't we link the jenkins.io documentation to guide beginners (instead of duplicating "get started" info here)?
> 
> ... thanks, having a look there ...


hmmm ... very quickly I remember looking at that doc a while ago and being put off by the "complexity" and the use of "docker-in-docker".

I might just end up creating my own Docker image based on my working "native Jenkins" install ... where I have initialAdminPassword available.

FYI: that native install was based in the "easy to understand" https://www.jenkins.io/doc/book/installing/linux/

**Comment by dduportal** [comment]
> > I guess you are expecting the README to point to https://www.jenkins.io/doc/book/installing/docker/ if I'm not mistaken.
> > Ping [@kmartens27](https://github.com/kmartens27) [@MarkEWaite](https://github.com/MarkEWaite) [@gounthar](https://github.com/gounthar) [@timja](https://github.com/timja) WDYT: Shouldn't we link the jenkins.io documentation to guide beginners (instead of duplicating "get started" info here)?
> 
> ... thanks, having a look there ...

oh wait, I realize the documentation at https://www.jenkins.io/doc/book/installing/docker/ seems terribly wrong as it mentions `dind`  😶‍🌫️  (ping @kmartens27 @gounthar ). 
I was focused on the "token retrieval).

Sorry for the false path

**Comment by dduportal** [comment]
> > > I guess you are expecting the README to point to https://www.jenkins.io/doc/book/installing/docker/ if I'm not mistaken.
> > > Ping [@kmartens27](https://github.com/kmartens27) [@MarkEWaite](https://github.com/MarkEWaite) [@gounthar](https://github.com/gounthar) [@timja](https://github.com/timja) WDYT: Shouldn't we link the jenkins.io documentation to guide beginners (instead of duplicating "get started" info here)?
> > 
> > 
> > ... thanks, having a look there ...
> 
> hmmm ... very quickly I remember looking at that doc a while ago and being put off by the "complexity" and the use of "docker-in-docker".
> 
> I might just end up creating my own Docker image based on my working "native Jenkins" install ... where I have initialAdminPassword available.
> 
> FYI: that native install was based in the "easy to understand" https://www.jenkins.io/doc/book/installing/linux/

@mjbright thousands of people (literally) are using the controller official image. So there is clearly an edge case here which is interesting to identify.

I use the command in my first command almost daily: if the token would be absent, we would be aware.


Let's diagnose in details:

- What host and Docker distribution are you using?
- What command/setup do you use to start the container?

**Comment by mjbright** [comment]
Ooops ... user misunderstanding ... or rather forgetting, but the README.md is incorrect.

In fact I had already entered the initialAdminPassword and forgotten this.

**So**, there is no token information in the jenkins container logs - the README.md is incorrect on this point.

But, using
   ```docker exec -it jenkins cat /var/jenkins_home/secrets/initialAdminPassword``` 
I was able to pickup the initial password.

The README.md needs to be updated to reflect this.

**Comment by mjbright** [comment]
> > > > I guess you are expecting the README to point to https://www.jenkins.io/doc/book/installing/docker/ if I'm not mistaken.
> > > > Ping [@kmartens27](https://github.com/kmartens27) [@MarkEWaite](https://github.com/MarkEWaite) [@gounthar](https://github.com/gounthar) [@timja](https://github.com/timja) WDYT: Shouldn't we link the jenkins.io documentation to guide beginners (instead of duplicating "get started" info here)?
> > > 
> > > 
> > > ... thanks, having a look there ...
> > 
> > 
> > hmmm ... very quickly I remember looking at that doc a while ago and being put off by the "complexity" and the use of "docker-in-docker".
> > I might just end up creating my own Docker image based on my working "native Jenkins" install ... where I have initialAdminPassword available.
> > FYI: that native install was based in the "easy to understand" https://www.jenkins.io/doc/book/installing/linux/
> 
> [@mjbright](https://github.com/mjbright) thousands of people (literally) are using the controller official image. So there is clearly an edge case here which is interesting to identify.
> 
> I use the command in my first command almost daily: if the token would be absent, we would be aware.
> 
> Let's diagnose in details:
> 
>     * What host and Docker distribution are you using?
> 
>     * What command/setup do you use to start the container?

Again, as stated earlier, I was running the command from the README (with addition of ```--name jenkins```):

```docker run -d -v jenkins_home:/var/jenkins_home --name jenkins -p 8080:8080 -p 50000:50000 --restart=on-failure jenkins/jenkins:lts-jdk17```

Not an issue but here's the Docker CE version I'm running:
```
Client: Docker Engine - Community
 Version:           28.2.2
 API version:       1.50
 Go version:        go1.24.3
 Git commit:        e6534b4
 Built:             Fri May 30 12:07:27 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          28.2.2
  API version:      1.50 (minimum version 1.24)
  Go version:       go1.24.3
  Git commit:       45873be
  Built:            Fri May 30 12:07:27 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.27
  GitCommit:        05044ec0a9a75232cad458027ca83437aae3f4da
 runc:
  Version:          1.2.5
  GitCommit:        v1.2.5-0-g59923ef
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by dduportal** [comment]
Good, it makes sense now and your problem is solved!

Would you be willing to propose a change to this README?
As someone I know use to say « you know what you know »: your fresh perspective would be really useful here! (I don’t mind doing it but with my habits it could mislead newcomers)

**Comment by gounthar** [comment]
In any case, we still have the [quickstart-tutorials repository](https://github.com/jenkins-docs/quickstart-tutorials) that helps get a Jenkins controller and agent up and running quickly with Docker Compose. While it's not aimed at you, since you're familiar with Jenkins and Docker, it could serve as inspiration for others. 🤷

**Comment by mjbright** [comment]
Hi @dduportal, sure, I hate dangling issues with vacuous "it works now" comments !
I was busy finishing off a Terraform class.

So my final take is
- the documentation is correct (**surprise!!**)
- the token does appear in the container logs - until it has been used - that makes good sense.

What I would suggest as a change to the README.md to make it idiot proof (i.e. mjbright proof), is instead of:

```
This will run Jenkins in detached mode with port forwarding and volume added. You can access logs with command 'docker logs CONTAINER_ID' in order to check first login token. ID of container will be returned from output of command above.
```

it reads something like:
```
An initial admin password is generated which is visible by using 'docker logs CONTAINER_ID'.

Initially you should see a line something like:
'Jenkins initial setup is required. An admin user has been created and a password generated.
Please use the following password to proceed to installation:'

**NOTE:** For security reasons - once the initial admin password has been used to log into the web console, it will no longer be visible in the logs.
```

**Comment by mjbright** [comment]
> > > I guess you are expecting the README to point to https://www.jenkins.io/doc/book/installing/docker/ if I'm not mistaken.
> > > Ping [@kmartens27](https://github.com/kmartens27) [@MarkEWaite](https://github.com/MarkEWaite) [@gounthar](https://github.com/gounthar) [@timja](https://github.com/timja) WDYT: Shouldn't we link the jenkins.io documentation to guide beginners (instead of duplicating "get started" info here)?
> > 
> > 
> > ... thanks, having a look there ...
> 
> oh wait, I realize the documentation at https://www.jenkins.io/doc/book/installing/docker/ seems terribly wrong as it mentions `dind` 😶‍🌫️ (ping [@kmartens27](https://github.com/kmartens27) [@gounthar](https://github.com/gounthar) ). I was focused on the "token retrieval).
> 
> Sorry for the false path

Actually not at all, as one of my use cases is to run Terraform and Docker from Jenkins, so the DIND approach is ultimately what I'm doing.

In the past I found that "installing docker" page off putting but I realize that with simple copy pasting into a bash script, and then modifying as I wish it's exactly what I want.

A separate issue of course, but maybe providing a simple bash script in that page would be a useful addition - for people who don't read documentation like myself ...

**Comment by lemeurherveCB** [comment]
- @mjbright does https://github.com/jenkinsci/docker/pull/2044 (recently merged) address your concerns? If so, this issue can be closed.

**Comment by dduportal** [comment]
> Hi [@dduportal](https://github.com/dduportal), sure, I hate dangling issues with vacuous "it works now" comments ! I was busy finishing off a Terraform class.
> 
> So my final take is
> 
>     * the documentation is correct (**surprise!!**)
> 
>     * the token does appear in the container logs - until it has been used - that makes good sense.
> 
> 
> What I would suggest as a change to the README.md to make it idiot proof (i.e. mjbright proof), is instead of:
> 
> ```
> This will run Jenkins in detached mode with port forwarding and volume added. You can access logs with command 'docker logs CONTAINER_ID' in order to check first login token. ID of container will be returned from output of command above.
> ```
> 
> it reads something like:
> 
> ```
> An initial admin password is generated which is visible by using 'docker logs CONTAINER_ID'.
> 
> Initially you should see a line something like:
> 'Jenkins initial setup is required. An admin user has been created and a password generated.
> Please use the following password to proceed to installation:'
> 
> **NOTE:** For security reasons - once the initial admin password has been used to log into the web console, it will no longer be visible in the logs.
> ```

Sorry @mjbright I totally forgot to answer you and then I got caught up in other things.
The answer was "yes"  but looks like https://github.com/jenkinsci/docker/pull/2044 did stole your work.
=> you still deserve credits for raising the issue, stating clearly the issue and guiding the goal. Thanks for your contribution!



Thanks @lemeurherveCB for triage! Let's wait for @mjbright answer to close!

**Comment by lemeurherve** [comment]
@mjbright gentle ping 🙂

**Comment by lemeurherve** [comment]
With https://github.com/jenkinsci/docker/pull/2044 and the more complete jenkins.io doc linked in the README with https://github.com/jenkinsci/docker/pull/2079 there is nothing left to do about this issue.

Closing as it's been a while we did not get feedback from @mjbright, and to not let people think this issue should be worked on anymore.
